apiVersion: application.sotoon.ir/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  image: nginx:latest
  replicas: 3
  httpPort: 80
  domains:
    - host: nginx.local
      path: /
      ssl:
        enabled: true
